<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="28" started-at="2018-10-28T12:21:20Z" finished-at="2018-10-28T12:21:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="28" started-at="2018-10-28T12:21:20Z" finished-at="2018-10-28T12:21:20Z">
      <class name="testcases.BaseTest">
        <test-method status="FAIL" signature="_beforeSuite()[pri:0, instance:testcases.BaseTest@194d431]" name="_beforeSuite" is-config="true" duration-ms="20415" started-at="2018-10-28T12:20:59Z" finished-at="2018-10-28T12:21:20Z">
          <exception class="framework.Helper$FrameworkException">
            <full-stacktrace>
              <![CDATA[msgExpected[sadf] Actual[haer]
at framework.Helper.assertAreEqual(Helper.java:97)
at testcases.BaseTest._beforeSuite(BaseTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- framework.Helper$FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _beforeSuite -->
        <test-method status="SKIP" signature="test()[pri:0, instance:testcases.BaseTest@194d431]" name="test" duration-ms="0" started-at="2018-10-28T12:21:20Z" finished-at="2018-10-28T12:21:20Z">
          <exception class="framework.Helper$FrameworkException">
            <full-stacktrace>
              <![CDATA[msgExpected[sadf] Actual[haer]
at framework.Helper.assertAreEqual(Helper.java:97)
at testcases.BaseTest._beforeSuite(BaseTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- framework.Helper$FrameworkException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="SKIP" signature="_afterSuite()[pri:0, instance:testcases.BaseTest@194d431]" name="_afterSuite" is-config="true" duration-ms="0" started-at="2018-10-28T12:21:20Z" finished-at="2018-10-28T12:21:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _afterSuite -->
      </class> <!-- testcases.BaseTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
